version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/wait-for-db.sh", "db", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./testissue:/app/testissue
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/mydatabase

volumes:
  postgres_data:
